// =============================================================================
// ILPEP — Indian Loyalty Points Exchange Platform
// Ledger Accounting Service — Journal Entry Model
//
// Double-entry bookkeeping header. Every exchange transaction produces exactly
// one JournalEntry whose total_debit MUST equal total_credit.
// Maps to: PostgreSQL table `journal_entries` (see 001_initial_schema.sql)
// =============================================================================

package models

import (
	"errors"
	"fmt"
	"math"
	"time"
)

// =============================================================================
// Constants
// =============================================================================

// EntryType classifies the journal entry for reporting and filtering.
type EntryType string

const (
	EntryTypeExchange   EntryType = "EXCHANGE"   // Standard point-to-wallet exchange
	EntryTypeRefund     EntryType = "REFUND"      // Reversal of a previous exchange
	EntryTypeAdjustment EntryType = "ADJUSTMENT"  // Manual correction by compliance officer
)

// ValidEntryTypes is the set of allowed entry type values.
var ValidEntryTypes = map[EntryType]bool{
	EntryTypeExchange:   true,
	EntryTypeRefund:     true,
	EntryTypeAdjustment: true,
}

// =============================================================================
// Errors
// =============================================================================

var (
	ErrDebitCreditMismatch = errors.New("total_debit must equal total_credit (double-entry invariant)")
	ErrInvalidEntryType    = errors.New("invalid entry type: must be EXCHANGE, REFUND, or ADJUSTMENT")
	ErrInvalidTxnID        = errors.New("txn_id is required and must be a valid UUID string")
	ErrNegativeAmount      = errors.New("debit and credit amounts must be non-negative")
	ErrZeroAmount          = errors.New("total_debit and total_credit must be greater than zero")
)

// =============================================================================
// JournalEntry Struct
// =============================================================================

// JournalEntry represents a double-entry bookkeeping header record.
//
// Business Rules:
//   - Every JournalEntry is linked to exactly one exchange_transaction via TxnID.
//   - TotalDebit MUST equal TotalCredit (enforced by CHECK constraint in DB and
//     by Validate() at the application layer).
//   - Once created, journal entries are immutable for audit compliance.
//
// Database Mapping:
//
//	entry_id     → EntryID     (UUID, auto-generated by PostgreSQL)
//	txn_id       → TxnID       (UUID, FK to exchange_transactions)
//	entry_type   → EntryType   (VARCHAR: EXCHANGE | REFUND | ADJUSTMENT)
//	total_debit  → TotalDebit  (DECIMAL(18,2))
//	total_credit → TotalCredit (DECIMAL(18,2))
//	created_at   → CreatedAt   (TIMESTAMPTZ)
type JournalEntry struct {
	EntryID     string    `json:"entry_id"     db:"entry_id"`
	TxnID       string    `json:"txn_id"       db:"txn_id"`
	EntryType   EntryType `json:"entry_type"   db:"entry_type"`
	TotalDebit  float64   `json:"total_debit"  db:"total_debit"`
	TotalCredit float64   `json:"total_credit" db:"total_credit"`
	CreatedAt   time.Time `json:"created_at"   db:"created_at"`
}

// =============================================================================
// Validation
// =============================================================================

// Validate checks all business rules before persisting a JournalEntry.
//
// Rules enforced:
//  1. TxnID must be non-empty (FK to exchange_transactions)
//  2. EntryType must be one of: EXCHANGE, REFUND, ADJUSTMENT
//  3. TotalDebit and TotalCredit must be > 0
//  4. TotalDebit MUST equal TotalCredit (double-entry invariant)
//
// The debit/credit equality check uses a small epsilon (0.001) to handle
// floating-point precision issues in decimal arithmetic.
func (je *JournalEntry) Validate() error {
	// 1. Transaction ID is required
	if je.TxnID == "" {
		return ErrInvalidTxnID
	}

	// 2. Entry type must be valid
	if !ValidEntryTypes[je.EntryType] {
		return fmt.Errorf("%w: got '%s'", ErrInvalidEntryType, je.EntryType)
	}

	// 3. Amounts must be positive
	if je.TotalDebit < 0 || je.TotalCredit < 0 {
		return ErrNegativeAmount
	}
	if je.TotalDebit == 0 || je.TotalCredit == 0 {
		return ErrZeroAmount
	}

	// 4. CRITICAL: Double-entry invariant — debit must equal credit
	//    Uses epsilon comparison for floating-point safety
	const epsilon = 0.001
	if math.Abs(je.TotalDebit-je.TotalCredit) > epsilon {
		return fmt.Errorf(
			"%w: debit=%.2f, credit=%.2f, diff=%.4f",
			ErrDebitCreditMismatch,
			je.TotalDebit,
			je.TotalCredit,
			je.TotalDebit-je.TotalCredit,
		)
	}

	return nil
}

// =============================================================================
// Constructor
// =============================================================================

// NewJournalEntry creates a new JournalEntry with validation.
//
// EntryID and CreatedAt are left empty — they are generated by PostgreSQL
// (gen_random_uuid() and NOW() respectively) upon INSERT.
//
// Returns an error if the double-entry invariant is violated or if
// any other validation rule fails.
func NewJournalEntry(txnID string, entryType EntryType, totalDebit, totalCredit float64) (*JournalEntry, error) {
	entry := &JournalEntry{
		TxnID:       txnID,
		EntryType:   entryType,
		TotalDebit:  totalDebit,
		TotalCredit: totalCredit,
	}

	if err := entry.Validate(); err != nil {
		return nil, err
	}

	return entry, nil
}

// =============================================================================
// Database Interface
// =============================================================================

// JournalEntryRepository defines the data access contract for journal entries.
//
// Implementations should use serializable isolation and row-level locking
// where concurrent transactions might affect the same records.
type JournalEntryRepository interface {
	// Create inserts a new journal entry within a transaction context.
	// The entry_id is generated by PostgreSQL and returned in the struct.
	// This MUST be called within the same DB transaction as the corresponding
	// exchange_transaction and ledger_lines inserts (atomic commit).
	Create(entry *JournalEntry) error

	// GetByID retrieves a journal entry by its primary key.
	GetByID(entryID string) (*JournalEntry, error)

	// GetByTxnID retrieves the journal entry for a specific transaction.
	// Returns nil if no entry exists for the given transaction ID.
	GetByTxnID(txnID string) (*JournalEntry, error)

	// ListByDateRange retrieves all journal entries created within the
	// specified time range. Used for reconciliation and compliance reporting.
	ListByDateRange(start, end time.Time) ([]*JournalEntry, error)

	// ListByEntryType retrieves journal entries filtered by type (EXCHANGE,
	// REFUND, ADJUSTMENT). Used for audit and financial analysis.
	ListByEntryType(entryType EntryType) ([]*JournalEntry, error)
}

// =============================================================================
// Helper Methods
// =============================================================================

// IsBalanced returns true if the journal entry satisfies the double-entry
// invariant (total_debit == total_credit within floating-point epsilon).
func (je *JournalEntry) IsBalanced() bool {
	const epsilon = 0.001
	return math.Abs(je.TotalDebit-je.TotalCredit) <= epsilon
}

// String returns a human-readable representation for logging and debugging.
func (je *JournalEntry) String() string {
	return fmt.Sprintf(
		"JournalEntry{ID=%s, Txn=%s, Type=%s, Debit=%.2f, Credit=%.2f, Balanced=%v}",
		je.EntryID, je.TxnID, je.EntryType,
		je.TotalDebit, je.TotalCredit, je.IsBalanced(),
	)
}
