// =============================================================================
// ILPEP — Indian Loyalty Points Exchange Platform
// Ledger Accounting Service — Ledger Line Model
//
// Individual debit/credit line items within a journal entry.
// Each line targets a specific account (e.g., USER_POINTS_LIABILITY, REVENUE).
// Enforces: each line is either a debit OR credit, never both.
// Maps to: PostgreSQL table `ledger_lines` (see 001_initial_schema.sql)
// =============================================================================

package models

import (
	"errors"
	"fmt"
)

// =============================================================================
// Account Name Constants
// =============================================================================

// AccountName represents a named account in the double-entry ledger.
// These correspond to the standard chart of accounts for ILPEP.
type AccountName string

const (
	// User-facing accounts
	AccountUserPointsLiability AccountName = "USER_POINTS_LIABILITY" // Points owed to user
	AccountUserWallet          AccountName = "USER_WALLET"           // User's INR wallet balance

	// Revenue accounts
	AccountRevenue    AccountName = "REVENUE"    // Platform service fee revenue
	AccountServiceFee AccountName = "SERVICE_FEE" // Service fee charged on exchange

	// Partner accounts
	AccountPartnerReceivables AccountName = "PARTNER_RECEIVABLES" // Amount receivable from partner
	AccountPartnerPayables    AccountName = "PARTNER_PAYABLES"    // Amount payable to partner

	// Tax accounts (GST)
	AccountGSTPayable  AccountName = "GST_PAYABLE"  // Total GST liability
	AccountCGSTPayable AccountName = "CGST_PAYABLE"  // Central GST (9% intra-state)
	AccountSGSTPayable AccountName = "SGST_PAYABLE"  // State GST (9% intra-state)
	AccountIGSTPayable AccountName = "IGST_PAYABLE"  // Integrated GST (18% inter-state)

	// Adjustment accounts
	AccountSuspense   AccountName = "SUSPENSE"   // Temporary holding for unresolved items
	AccountRefund     AccountName = "REFUND"      // Refund-related entries
)

// ValidAccountNames is the set of allowed account names in ledger lines.
var ValidAccountNames = map[AccountName]bool{
	AccountUserPointsLiability: true,
	AccountUserWallet:          true,
	AccountRevenue:             true,
	AccountServiceFee:          true,
	AccountPartnerReceivables:  true,
	AccountPartnerPayables:     true,
	AccountGSTPayable:          true,
	AccountCGSTPayable:         true,
	AccountSGSTPayable:         true,
	AccountIGSTPayable:         true,
	AccountSuspense:            true,
	AccountRefund:              true,
}

// =============================================================================
// Errors
// =============================================================================

var (
	ErrInvalidAccountName   = errors.New("invalid account name")
	ErrBothDebitAndCredit    = errors.New("a ledger line must be either debit OR credit, not both")
	ErrNoDebitOrCredit       = errors.New("a ledger line must have either a debit or credit amount > 0")
	ErrInvalidEntryID       = errors.New("entry_id is required (FK to journal_entries)")
	ErrNegativeLedgerAmount = errors.New("debit and credit amounts must be non-negative")
)

// =============================================================================
// LedgerLine Struct
// =============================================================================

// LedgerLine represents a single debit or credit line item in the ledger.
//
// Business Rules:
//   - Each line is linked to exactly one JournalEntry via EntryID.
//   - A line is EITHER a debit OR a credit, never both (mutual exclusion).
//   - This is enforced by the CHECK constraint in PostgreSQL and by Validate()
//     at the application layer.
//
// Database Mapping:
//
//	line_id      → LineID      (UUID, auto-generated by PostgreSQL)
//	entry_id     → EntryID     (UUID, FK to journal_entries)
//	account_name → AccountName (VARCHAR: e.g., 'USER_POINTS_LIABILITY')
//	debit        → Debit       (DECIMAL(18,2), default 0.00)
//	credit       → Credit      (DECIMAL(18,2), default 0.00)
type LedgerLine struct {
	LineID      string      `json:"line_id"      db:"line_id"`
	EntryID     string      `json:"entry_id"     db:"entry_id"`
	AccountName AccountName `json:"account_name" db:"account_name"`
	Debit       float64     `json:"debit"        db:"debit"`
	Credit      float64     `json:"credit"       db:"credit"`
}

// =============================================================================
// Validation
// =============================================================================

// Validate checks all business rules before persisting a LedgerLine.
//
// Rules enforced:
//  1. EntryID must be non-empty (FK to journal_entries)
//  2. AccountName must be one of the predefined valid names
//  3. Debit and Credit must be non-negative
//  4. Exactly one of Debit or Credit must be > 0 (mutual exclusion)
func (ll *LedgerLine) Validate() error {
	// 1. Entry ID is required
	if ll.EntryID == "" {
		return ErrInvalidEntryID
	}

	// 2. Account name must be valid
	if !ValidAccountNames[ll.AccountName] {
		return fmt.Errorf("%w: got '%s'", ErrInvalidAccountName, ll.AccountName)
	}

	// 3. Amounts must be non-negative
	if ll.Debit < 0 || ll.Credit < 0 {
		return ErrNegativeLedgerAmount
	}

	// 4. Mutual exclusion: debit XOR credit
	if ll.Debit > 0 && ll.Credit > 0 {
		return fmt.Errorf(
			"%w: debit=%.2f, credit=%.2f",
			ErrBothDebitAndCredit, ll.Debit, ll.Credit,
		)
	}
	if ll.Debit == 0 && ll.Credit == 0 {
		return ErrNoDebitOrCredit
	}

	return nil
}

// =============================================================================
// Constructors
// =============================================================================

// NewDebitLine creates a validated ledger line with a debit entry.
//
// Used when recording flows INTO an account (e.g., debiting
// USER_POINTS_LIABILITY when consuming user points).
func NewDebitLine(entryID string, account AccountName, amount float64) (*LedgerLine, error) {
	line := &LedgerLine{
		EntryID:     entryID,
		AccountName: account,
		Debit:       amount,
		Credit:      0,
	}
	if err := line.Validate(); err != nil {
		return nil, err
	}
	return line, nil
}

// NewCreditLine creates a validated ledger line with a credit entry.
//
// Used when recording flows OUT OF an account (e.g., crediting
// REVENUE when earning service fees).
func NewCreditLine(entryID string, account AccountName, amount float64) (*LedgerLine, error) {
	line := &LedgerLine{
		EntryID:     entryID,
		AccountName: account,
		Debit:       0,
		Credit:      amount,
	}
	if err := line.Validate(); err != nil {
		return nil, err
	}
	return line, nil
}

// =============================================================================
// Database Interface
// =============================================================================

// LedgerLineRepository defines the data access contract for ledger lines.
//
// All write operations MUST be called within the same DB transaction as
// the parent JournalEntry creation (atomic double-entry commit).
type LedgerLineRepository interface {
	// Create inserts a new ledger line. Must be called within the same
	// transaction as the parent JournalEntry insert.
	Create(line *LedgerLine) error

	// CreateBatch inserts multiple ledger lines in a single batch.
	// All lines must belong to the same journal entry.
	// Used by CommitExchangeTransaction() to insert all lines atomically.
	CreateBatch(lines []*LedgerLine) error

	// GetByEntryID retrieves all ledger lines for a journal entry.
	GetByEntryID(entryID string) ([]*LedgerLine, error)

	// GetByAccountName retrieves all ledger lines for a specific account.
	// Used for account-level reconciliation and balance checks.
	GetByAccountName(account AccountName) ([]*LedgerLine, error)

	// SumByAccount calculates the total debit and credit for an account.
	// Returns (totalDebit, totalCredit, error).
	// Used for trial balance and reconciliation reports.
	SumByAccount(account AccountName) (float64, float64, error)
}

// =============================================================================
// Helper Methods
// =============================================================================

// IsDebit returns true if this line records a debit (inflow to account).
func (ll *LedgerLine) IsDebit() bool {
	return ll.Debit > 0 && ll.Credit == 0
}

// IsCredit returns true if this line records a credit (outflow from account).
func (ll *LedgerLine) IsCredit() bool {
	return ll.Credit > 0 && ll.Debit == 0
}

// Amount returns the effective amount (debit or credit value).
func (ll *LedgerLine) Amount() float64 {
	if ll.Debit > 0 {
		return ll.Debit
	}
	return ll.Credit
}

// String returns a human-readable representation for logging and debugging.
func (ll *LedgerLine) String() string {
	side := "DEBIT"
	amount := ll.Debit
	if ll.IsCredit() {
		side = "CREDIT"
		amount = ll.Credit
	}
	return fmt.Sprintf(
		"LedgerLine{ID=%s, Entry=%s, Account=%s, %s=%.2f}",
		ll.LineID, ll.EntryID, ll.AccountName, side, amount,
	)
}

// =============================================================================
// Exchange Transaction Line Builder
// =============================================================================

// BuildExchangeLines creates the standard set of ledger lines for a
// point-to-wallet exchange transaction.
//
// Double-entry breakdown for an exchange:
//
//	DEBIT  USER_POINTS_LIABILITY   (gross value — points consumed)
//	CREDIT REVENUE                 (service fee earned)
//	CREDIT GST_PAYABLE             (GST on service fee)
//	CREDIT PARTNER_RECEIVABLES     (net amount due from partner)
//	CREDIT USER_WALLET             (net value credited to user wallet)
//
// The sum of all credits MUST equal the debit (double-entry invariant).
//
// Parameters:
//   - entryID: the parent JournalEntry ID
//   - grossValue: total INR value of exchanged points
//   - serviceFee: platform service fee
//   - gstAmount: GST on the service fee (18%)
//   - netValue: amount credited to user wallet (gross - fee - gst)
func BuildExchangeLines(
	entryID string,
	grossValue, serviceFee, gstAmount, netValue float64,
) ([]*LedgerLine, error) {

	lines := make([]*LedgerLine, 0, 4)

	// 1. DEBIT: Consume user's points liability
	debitLine, err := NewDebitLine(entryID, AccountUserPointsLiability, grossValue)
	if err != nil {
		return nil, fmt.Errorf("failed to create debit line: %w", err)
	}
	lines = append(lines, debitLine)

	// 2. CREDIT: Platform earns service fee revenue
	if serviceFee > 0 {
		revLine, err := NewCreditLine(entryID, AccountRevenue, serviceFee)
		if err != nil {
			return nil, fmt.Errorf("failed to create revenue line: %w", err)
		}
		lines = append(lines, revLine)
	}

	// 3. CREDIT: GST payable on the service fee
	if gstAmount > 0 {
		gstLine, err := NewCreditLine(entryID, AccountGSTPayable, gstAmount)
		if err != nil {
			return nil, fmt.Errorf("failed to create GST line: %w", err)
		}
		lines = append(lines, gstLine)
	}

	// 4. CREDIT: Net value into user's wallet
	if netValue > 0 {
		walletLine, err := NewCreditLine(entryID, AccountUserWallet, netValue)
		if err != nil {
			return nil, fmt.Errorf("failed to create wallet credit line: %w", err)
		}
		lines = append(lines, walletLine)
	}

	return lines, nil
}

// ValidateLineSet checks that a set of ledger lines for a single journal
// entry satisfies the double-entry invariant: sum(debits) == sum(credits).
func ValidateLineSet(lines []*LedgerLine) error {
	if len(lines) == 0 {
		return errors.New("line set cannot be empty")
	}

	var totalDebit, totalCredit float64
	for _, line := range lines {
		if err := line.Validate(); err != nil {
			return fmt.Errorf("invalid line for account %s: %w", line.AccountName, err)
		}
		totalDebit += line.Debit
		totalCredit += line.Credit
	}

	const epsilon = 0.001
	diff := totalDebit - totalCredit
	if diff > epsilon || diff < -epsilon {
		return fmt.Errorf(
			"line set violates double-entry: total_debit=%.2f, total_credit=%.2f, diff=%.4f",
			totalDebit, totalCredit, diff,
		)
	}

	return nil
}
